import type { Metadata } from "next";
import { Cairo } from "next/font/google"
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cairo = Cairo({
  subsets: ['arabic'],
  weight: ['200', '300', '500', '600', '900']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${cairo.className}`}
      >
        {children}
      </body>
    </html>
  );
}
